# Generated by Django 5.2.3 on 2025-06-23 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('unidadeMedida', models.CharField(choices=[('ton', 'Ton'), ('kg', 'Kilogram'), ('g', 'Gram'), ('mg', 'Milligram')], max_length=10)),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='plantio.tipoinsumo')),
            ],
        ),
    ]
