# Generated by Django 5.2.3 on 2025-06-23 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantio', '0002_cultura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Propriedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('endereco', models.CharField(max_length=255)),
                ('area_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dono', models.CharField(blank=True, max_length=100, null=True)),
                ('data_aquisicao', models.DateField()),
            ],
            options={
                'verbose_name': 'Propriedade',
                'verbose_name_plural': 'Propriedades',
                'ordering': ['nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='tipoinsumo',
            options={'verbose_name': 'Tipo de Insumo', 'verbose_name_plural': 'Tipos de Insumo'},
        ),
        migrations.CreateModel(
            name='Plantio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_plantio', models.DateField()),
                ('area_plantada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('planejado', 'Planejado'), ('em_andamento', 'Em Andamento'), ('concluido', 'Concluído')], default='planejado', max_length=20)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantio.cultura')),
                ('propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantio.propriedade')),
            ],
            options={
                'verbose_name': 'Plantio',
                'verbose_name_plural': 'Plantios',
                'ordering': ['data_plantio'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('cargo', models.CharField(blank=True, max_length=50, null=True)),
                ('Propriedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='plantio.propriedade')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('data_aquisicao', models.DateField()),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantio.funcionario')),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantio.propriedade')),
            ],
            options={
                'verbose_name': 'Tarefa',
                'verbose_name_plural': 'Tarefas',
                'ordering': ['data_aquisicao'],
            },
        ),
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_colheita', models.DateField()),
                ('quantidade_colhida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qualidade', models.CharField(blank=True, max_length=50, null=True)),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colheitas', to='plantio.tarefa')),
            ],
            options={
                'verbose_name': 'Colheita',
                'verbose_name_plural': 'Colheitas',
                'ordering': ['data_colheita'],
            },
        ),
        migrations.CreateModel(
            name='UsoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_uso', models.DateField()),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantio.insumo')),
                ('plantio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantio.plantio')),
            ],
            options={
                'verbose_name': 'Uso de Insumo',
                'verbose_name_plural': 'Uso de Insumos',
                'ordering': ['data_uso'],
            },
        ),
    ]
