# Generated by Django 5.2.3 on 2025-06-26 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantio', '0003_propriedade_alter_tipoinsumo_options_plantio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='plantio.tipoinsumo'),
        ),
    ]
